Added `Using new features` wiki page
DV8FromTheWorld/JDA-Website pull request #12
Opened 2022-02-20 20:48 UTC by freya022

This PR adds the "Using new features" wiki page, which uses JitPack to try out PR branches

2022-02-20 22:59 UTC, oliver276 requested changes

2022-02-20 22:59 UTC, oliver276 commented on mkdocs.yml
> +    - Using new features: using-jda/using-new-features.md
```suggestion
    - Using New Features: using-jda/using-new-features.md
```

2022-02-20 22:59 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +# Using new features
```suggestion
# Using New Features
```

2022-02-20 22:59 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +you might be interested in trying these features before they get released and/or test them.
```suggestion
When contributors are making new features, like introducing modals, 
you might be interested in trying out or testing these features before they get released.
```

2022-02-20 22:59 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +Of course, it is highly recommended that you use a build tool such as [Gradle](https://gradle.org) or [Maven](https://maven.apache.org)
```suggestion
It is still highly recommended that you use a build tool such as [Gradle](https://gradle.org) or [Maven](https://maven.apache.org)
```

2022-02-20 22:59 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +### Getting the necessary info
Please capitalise these headings

2022-02-20 22:59 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +So far we got:
```suggestion
So far we have:
```

2022-02-22 21:21 UTC, oliver276 approved these changes

2022-03-02 05:35 UTC, oliver276 requested changes
There are a few missing full stops/periods here.

It also feels a bit odd to continue the same example of Xirado's PR without showing what that example would look like at the end.

2022-03-02 05:35 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +Here the important part is `from Xirado:feature/modals`, you need to extract the PR author, which here is `xirado`
This sentence doesn't seem to make much sense.  I think it is fine to just say something like "You need the author's name, which here is \`Xirado\`."

2022-03-02 05:35 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +You then want to go in the `Commits` tab
```suggestion
Next, head to the `Commits` tab.
```

2022-03-02 05:35 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +You can now scroll down to the bottom, as to find the latest **commit hash**, it would look like this:
```suggestion
You can now scroll down to the bottom, as to find the latest **commit hash**.  It should look like this:
```

2022-03-02 05:35 UTC, oliver276 commented on docs/using-jda/using-new-features.md
> +=== "Maven"
Elsewhere in the wiki, Gradle has come before Maven.  This is probably something we should standardise.

2022-03-13 14:59 UTC, oliver276 approved these changes

2022-03-26 14:42 UTC, Aikovdp reviewed
Looks good to me! Just a few minor suggestions, you can do with those what you want.

2022-03-26 14:42 UTC, Aikovdp commented on docs/introduction/faq.md
> +    You can use JitPack to provide other branches of JDA as a dependency.  We have a tutorial on how to use it on [this wiki page](/using-jda/using-new-features)
```suggestion
    You can use JitPack to provide other branches of JDA as a dependency.  We have a tutorial on how to use it on [this wiki page](/using-jda/using-new-features).
```

2022-03-26 14:42 UTC, Aikovdp commented on docs/using-jda/using-new-features.md
> +Here you can see the 7 first chars of the latest commit are `36eea2a`.
```suggestion
Here you can see the 7 first characters of the latest commit are `36eea2a`.
```

2022-03-26 14:42 UTC, Aikovdp commented on docs/using-jda/using-new-features.md
> +You can now add the dependency to your favorite build tool, but before that, you will have to remove your current JDA dependency.
```suggestion
You can now add the dependency to your project using your favorite build tool, but don't forget to remove your current JDA dependency first.
```

2022-03-26 14:42 UTC, Aikovdp commented on docs/using-jda/using-new-features.md
> +* Version (7 char commit hash): `36eea2a`
```suggestion
* Version (7 character commit hash): `36eea2a`
```

2022-03-26 14:42 UTC, Aikovdp commented on mkdocs.yml
> +  - md_in_html
I don't think the `md_in_html` extension is being used here, only the `attr_list` one is necessary for those images. 
```suggestion
```

2022-03-29 09:53 UTC, Aikovdp approved these changes

2022-05-17 21:45 UTC, merged